# Generated by Django 6.0 on 2026-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_activity_club_counselingresource_disciplinepolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='staff_cvs/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='professional_development',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='vision.subject'),
        ),
    ]
